# Autoriser l'écoute sur toutes les interfaces (WiFi et Ethernet)
listener 1883 0.0.0.0

# Autoriser les connexions sans mot de passe pour les tests
allow_anonymous true

# Emplacement du stockage (optionnel)
persistence true
persistence_location /var/lib/mosquitto/
