#!/bin/sh

case "$1" in
start)
    echo "Starting WiFi"

    modprobe brcmfmac

    echo "Waiting for wlan0..."
    while ! ip link show wlan0 >/dev/null 2>&1; do
        sleep 1
    done

    ip link set wlan0 up

    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf

    udhcpc -i wlan0
    ;;
esac

exit 0
